@echo off
set BACKEND_PORT=8012
echo Starting Coin Lab Development Servers (inline)...
echo.
echo [Backend] Starting on port %BACKEND_PORT%...
start /b cmd /c "cd backend && .venv\Scripts\python.exe -m uvicorn app.main:app --host 127.0.0.1 --port %BACKEND_PORT%"
echo [Frontend] Starting on port 5173...
cd frontend && npm.cmd run dev
