@echo off
echo Starting Coin Lab Development Servers (inline)...
echo.
echo [Backend] Starting on port 8000...
start /b cmd /c "cd backend && .venv\Scripts\python.exe -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo [Frontend] Starting on port 5173...
cd frontend && npm.cmd run dev
