from enum import Enum

REQ_INVALID_PAYLOAD = "REQ_INVALID_PAYLOAD"
REQ_MISSING_FIELD = "REQ_MISSING_FIELD"
REQ_INVALID_ENUM = "REQ_INVALID_ENUM"
REQ_CONFLICT = "REQ_CONFLICT"
REQ_NOT_FOUND = "REQ_NOT_FOUND"
REQ_UNAUTHORIZED_MODE = "REQ_UNAUTHORIZED_MODE"
DSL_VALIDATION_FAILED = "DSL_VALIDATION_FAILED"
DSL_UNKNOWN_OPERATOR = "DSL_UNKNOWN_OPERATOR"
DSL_INVALID_TIMEFRAME_REF = "DSL_INVALID_TIMEFRAME_REF"
DSL_UNKNOWN_TOP_LEVEL_KEY = "DSL_UNKNOWN_TOP_LEVEL_KEY"
DSL_INVALID_ENUM = "DSL_INVALID_ENUM"
DSL_MISSING_REQUIRED_FIELD = "DSL_MISSING_REQUIRED_FIELD"
DSL_INVALID_THRESHOLD_RANGE = "DSL_INVALID_THRESHOLD_RANGE"
DSL_INVALID_TIMEFRAME_REFERENCE = "DSL_INVALID_TIMEFRAME_REFERENCE"
DSL_INVALID_PARTIAL_TP_SUM = "DSL_INVALID_PARTIAL_TP_SUM"
DSL_PLUGIN_AND_DSL_CONFLICT = "DSL_PLUGIN_AND_DSL_CONFLICT"
DSL_INVALID_CONDITION_DEPTH = "DSL_INVALID_CONDITION_DEPTH"
DSL_EMPTY_CONDITIONS = "DSL_EMPTY_CONDITIONS"
DSL_INVALID_SOURCE_REF = "DSL_INVALID_SOURCE_REF"
DSL_PLUGIN_LOAD_FAILED = "DSL_PLUGIN_LOAD_FAILED"
DSL_PLUGIN_CONTRACT_INVALID = "DSL_PLUGIN_CONTRACT_INVALID"
EXEC_SNAPSHOT_STALE = "EXEC_SNAPSHOT_STALE"
EXEC_DUPLICATE_SIGNAL_IGNORED = "EXEC_DUPLICATE_SIGNAL_IGNORED"
EXEC_ORDER_SUBMISSION_FAILED = "EXEC_ORDER_SUBMISSION_FAILED"
EXEC_LIMIT_NOT_FILLED_TIMEOUT = "EXEC_LIMIT_NOT_FILLED_TIMEOUT"
EXEC_FALLBACK_MARKET_FAILED = "EXEC_FALLBACK_MARKET_FAILED"
EXEC_POSITION_STATE_INVALID = "EXEC_POSITION_STATE_INVALID"
RISK_MAX_DRAWDOWN_REACHED = "RISK_MAX_DRAWDOWN_REACHED"
RISK_DAILY_LOSS_LIMIT_REACHED = "RISK_DAILY_LOSS_LIMIT_REACHED"
RISK_DUPLICATE_POSITION_BLOCKED = "RISK_DUPLICATE_POSITION_BLOCKED"
RISK_MAX_CONCURRENT_POSITIONS_REACHED = "RISK_MAX_CONCURRENT_POSITIONS_REACHED"
RISK_EMERGENCY_STOP_ACTIVE = "RISK_EMERGENCY_STOP_ACTIVE"
RISK_POSITION_SIZE_REJECTED = "RISK_POSITION_SIZE_REJECTED"
RISK_REENTRY_COOLDOWN_ACTIVE = "RISK_REENTRY_COOLDOWN_ACTIVE"
RISK_REENTRY_RESET_PENDING = "RISK_REENTRY_RESET_PENDING"
EVT_DUPLICATE_DROPPED = "EVT_DUPLICATE_DROPPED"
EVT_OUT_OF_ORDER_DROPPED = "EVT_OUT_OF_ORDER_DROPPED"
EVT_LAGGED_DROPPED = "EVT_LAGGED_DROPPED"
EVT_GAP_RECOVERY_INCOMPLETE = "EVT_GAP_RECOVERY_INCOMPLETE"
DATA_REQUIRED_TIMEFRAME_MISSING = "DATA_REQUIRED_TIMEFRAME_MISSING"
DATA_INDICATOR_BUILD_FAILED = "DATA_INDICATOR_BUILD_FAILED"
DATA_SYMBOL_DEGRADED = "DATA_SYMBOL_DEGRADED"
LIVE_CONFIRMATION_REQUIRED = "LIVE_CONFIRMATION_REQUIRED"
LIVE_API_KEY_MISSING = "LIVE_API_KEY_MISSING"
LIVE_ORDER_REJECTED_BY_EXCHANGE = "LIVE_ORDER_REJECTED_BY_EXCHANGE"
LIVE_MODE_SWITCH_BLOCKED = "LIVE_MODE_SWITCH_BLOCKED"
SYS_DB_WRITE_FAILED = "SYS_DB_WRITE_FAILED"
SYS_QUEUE_OVERFLOW = "SYS_QUEUE_OVERFLOW"
SYS_WS_DISCONNECTED = "SYS_WS_DISCONNECTED"
SYS_TIMEOUT = "SYS_TIMEOUT"
SYS_UNHANDLED_EXCEPTION = "SYS_UNHANDLED_EXCEPTION"


class ErrorCode(str, Enum):
    REQ_INVALID_PAYLOAD = REQ_INVALID_PAYLOAD
    REQ_MISSING_FIELD = REQ_MISSING_FIELD
    REQ_INVALID_ENUM = REQ_INVALID_ENUM
    REQ_CONFLICT = REQ_CONFLICT
    REQ_NOT_FOUND = REQ_NOT_FOUND
    REQ_UNAUTHORIZED_MODE = REQ_UNAUTHORIZED_MODE
    DSL_VALIDATION_FAILED = DSL_VALIDATION_FAILED
    DSL_UNKNOWN_OPERATOR = DSL_UNKNOWN_OPERATOR
    DSL_INVALID_TIMEFRAME_REF = DSL_INVALID_TIMEFRAME_REF
    DSL_UNKNOWN_TOP_LEVEL_KEY = DSL_UNKNOWN_TOP_LEVEL_KEY
    DSL_INVALID_ENUM = DSL_INVALID_ENUM
    DSL_MISSING_REQUIRED_FIELD = DSL_MISSING_REQUIRED_FIELD
    DSL_INVALID_THRESHOLD_RANGE = DSL_INVALID_THRESHOLD_RANGE
    DSL_INVALID_TIMEFRAME_REFERENCE = DSL_INVALID_TIMEFRAME_REFERENCE
    DSL_INVALID_PARTIAL_TP_SUM = DSL_INVALID_PARTIAL_TP_SUM
    DSL_PLUGIN_AND_DSL_CONFLICT = DSL_PLUGIN_AND_DSL_CONFLICT
    DSL_INVALID_CONDITION_DEPTH = DSL_INVALID_CONDITION_DEPTH
    DSL_EMPTY_CONDITIONS = DSL_EMPTY_CONDITIONS
    DSL_INVALID_SOURCE_REF = DSL_INVALID_SOURCE_REF
    DSL_PLUGIN_LOAD_FAILED = DSL_PLUGIN_LOAD_FAILED
    DSL_PLUGIN_CONTRACT_INVALID = DSL_PLUGIN_CONTRACT_INVALID
    RISK_REENTRY_COOLDOWN_ACTIVE = RISK_REENTRY_COOLDOWN_ACTIVE
    RISK_REENTRY_RESET_PENDING = RISK_REENTRY_RESET_PENDING
    LIVE_CONFIRMATION_REQUIRED = LIVE_CONFIRMATION_REQUIRED
    LIVE_API_KEY_MISSING = LIVE_API_KEY_MISSING
    LIVE_MODE_SWITCH_BLOCKED = LIVE_MODE_SWITCH_BLOCKED
    SYS_UNHANDLED_EXCEPTION = SYS_UNHANDLED_EXCEPTION

ERROR_CODE_HTTP_STATUS = {
    REQ_INVALID_PAYLOAD: 400,
    REQ_MISSING_FIELD: 400,
    REQ_INVALID_ENUM: 400,
    REQ_UNAUTHORIZED_MODE: 400,
    REQ_NOT_FOUND: 404,
    REQ_CONFLICT: 409,
    DSL_VALIDATION_FAILED: 400,
    DSL_UNKNOWN_OPERATOR: 400,
    DSL_INVALID_TIMEFRAME_REF: 400,
    DSL_UNKNOWN_TOP_LEVEL_KEY: 400,
    DSL_INVALID_ENUM: 400,
    DSL_MISSING_REQUIRED_FIELD: 400,
    DSL_INVALID_THRESHOLD_RANGE: 400,
    DSL_INVALID_TIMEFRAME_REFERENCE: 400,
    DSL_INVALID_PARTIAL_TP_SUM: 400,
    DSL_PLUGIN_AND_DSL_CONFLICT: 400,
    DSL_INVALID_CONDITION_DEPTH: 400,
    DSL_EMPTY_CONDITIONS: 400,
    DSL_INVALID_SOURCE_REF: 400,
    DSL_PLUGIN_LOAD_FAILED: 400,
    DSL_PLUGIN_CONTRACT_INVALID: 400,
    LIVE_CONFIRMATION_REQUIRED: 400,
    LIVE_API_KEY_MISSING: 400,
    LIVE_MODE_SWITCH_BLOCKED: 400,
    RISK_REENTRY_COOLDOWN_ACTIVE: 400,
    RISK_REENTRY_RESET_PENDING: 400,
    SYS_DB_WRITE_FAILED: 500,
    SYS_QUEUE_OVERFLOW: 500,
    SYS_WS_DISCONNECTED: 500,
    SYS_TIMEOUT: 500,
    SYS_UNHANDLED_EXCEPTION: 500,
}

def status_code_for_error(error_code: str) -> int:
    return ERROR_CODE_HTTP_STATUS.get(error_code, 400)
